### ISSUE TITLE
load(filename) not working properly

### ISSUE THREAD

**Issue by davideprose** [VikingScientist/MatlabLR#3]
lr.load(filename) 

Malab does not recognize the object/class lr if the command is called in a new script, e.g. for opening a previously saved LR object

**Comment by VikingScientist** [comment]
The following syntax should work:

``` matlab
% create a test LR mesh
lr =LRSplineSurface([3,3], [7,7]);
lr.refine(32);
lr.refine(32);
lr.refine(32);

% save it to file and clear from memory
lr.save("out.lr");
clear;

% create an empty LR object and load it from file
lr = LRSplineSurface();
lr.load("out.lr")
```

**Comment by VikingScientist** [comment]
An alternative syntax would be to have it be
``` matlab
lr = LRSplineSurface.load('out.lr')
```
in which case `load()` would have to be a static method. It might be a bit more intuitive so I might make the change.

**Comment by davideprose** [comment]
the first sintax works for LRSplineSurface, but in LRNURBSSurface the command lr.load("out.lr") gives Matlab error:

Error using lrsplinesurface_interface
Input must be a real uint64 scalar.

Error in LRNURBSSurface/load (line 140)
			lrsplinesurface_interface('load', this.objectHandle, filename);

Still, the syntax of the the save and load methods are identical in the the LRSplineSurface and LRNURBSSurface Matlab wrappers

**Comment by VikingScientist** [comment]
Ah yes. There is a good old fashioned error in the NURBS case. It boils down to the fact taht `LRSplineSurface` creates an empty instance (see the constructor with `nargin==0`), while `LRNURBSSurface` creates a null pointer.

I will fix this.

**Comment by VikingScientist** [comment]
Fixed is now commited.

I've settled on the static load method which means that the syntax should be

``` matlab

lr = LRNURBSSurface.load('out.lr');
```

**Comment by davideprose** [comment]
tested with success

thanks
